org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# HTTP/HTTPS 代理（给 Gradle 和所有插件用）
systemProp.http.proxyHost=10.206.193.215
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=10.206.193.215
systemProp.https.proxyPort=7890
kotlin.incremental=false
